# Site settings
title: Scrum Reports
author: NumbScrums
email:
description: Scrum report Prototype for Build Day 2015
baseurl: "/scrum/" # the subpath of your site, e.g. /blog/
url: "http://www.landregistryconcept.co.uk" # the base hostname & protocol for your site
theme: cerulean


# Build settings
markdown: kramdown
permalink: pretty
exclude: [vendor]
